In [1]:
import numpy as np

In [8]:
data = np.random.rand(2,3,2)

In [10]:
data

array([[[0.61865527, 0.92002565],
        [0.18421304, 0.43349629],
        [0.60818747, 0.67721962]],

       [[0.82105889, 0.42830506],
        [0.24118288, 0.28420221],
        [0.32665765, 0.3894787 ]]])

In [3]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [4]:
np.full((2,3,4),3)

array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]])

In [6]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
data.shape

(2, 3, 2)

In [13]:
data.size

12

In [14]:
data.dtype

dtype('float64')