In [ ]:
bharadwaj = []
i = 1
sum_ = 1
while i<10:
    sum_ = sum_ + i
    bharadwaj.append(sum_)
return sum_

In [ ]:
bharadwaj

In [ ]:
def double(q):
    return q * 2

In [ ]:
double(2)

# pandas and numpy

In [1]:
import pandas as pd
import numpy as np

In [3]:
y = np.arange(25)

In [4]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
bank = np.argpartition(y,1)

In [9]:
bank

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24], dtype=int64)

In [10]:
d = [12, 10, 12,  0,  6,  8,  9,  1, 16,  4,  6,  0]

In [12]:
q = np.array(d)

In [14]:
king = np.argpartition()

In [15]:
king

array([ 3,  7, 11,  9,  4, 10,  5,  6,  8,  1,  2,  0], dtype=int64)